### ISSUE TITLE
[Bug] A lot of characters in password field returns 413

### ISSUE THREAD

**Issue by axdra** [ATholin/fika#19]
If you put a alot of characters in the password for editing it return 413 :( 🥺🥺🥺🥺🥺🥺
![MicrosoftTeams-image](https://user-images.githubusercontent.com/54435884/80946068-8963b500-8ded-11ea-9bae-c75648d67768.png)

**Comment by ATholin** [comment]
Thanks. This is due to the request not validating the password input length.
